# Generated by Django 4.2.7 on 2023-12-07 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestrante', models.CharField(blank=True, default='Palestrante Default', max_length=50, null=True)),
                ('titulo', models.CharField(default='Titulo Default', max_length=200, null=True)),
                ('desc', models.CharField(default='Descrição Default', max_length=500, null=True)),
                ('link', models.URLField(blank=True, default='link default', max_length=100, null=True)),
                ('data', models.DateField(blank=True, default=datetime.date(2023, 12, 7), null=True)),
                ('evento_img', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
            ],
        ),
    ]
