# Generated by Django 4.2.7 on 2023-12-08 22:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_organizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='buscar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizador',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 8), null=True),
        ),
    ]
