# Generated by Django 4.2.7 on 2023-12-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizador', '0002_organizador_buscar_alter_organizador_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='buscar',
        ),
    ]
