# Generated by Django 4.2.7 on 2023-12-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizador', '0004_organizador_buscar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='buscar',
        ),
    ]
