# Generated by Django 4.2.7 on 2023-12-13 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizador', '0005_remove_organizador_buscar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 13), null=True),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='link',
            field=models.URLField(blank=True, default='Link Default', max_length=100, null=True),
        ),
    ]
