# Generated by Django 4.2.7 on 2023-12-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizador', '0006_alter_organizador_data_alter_organizador_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 14), null=True),
        ),
    ]
